### ISSUE TITLE
2 agency names the same in the GTFS file causes an exception in GTFSFileProcessor

### ISSUE THREAD

**Issue by scrudden** [TheTransitClock/transitime#117]
This exception is thrown when trying to process the GTFS from Metro Transit. This is because the agency_name is used as the primary key rather than the agency_id.

```
org.hibernate.NonUniqueObjectException: A different object with the same identifier value was already associated with the session : [org.transitclock.db.structs.Agency#Agency [configRev=0, agencyId=1, agencyName=Metro Transit, agencyUrl=http://www.metrotransit.org, agencyTimezone=America/Chicago, agencyLang=EN, agencyPhone=null, agencyFareUrl=null, extent=[minLat=44.70714, maxLat=45.56013, minLon=-94.15737, maxLon=-92.80558]]]
        at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:182) ~[Core.jar:na]
        at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:138) ~[Core.jar:na]
        at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:209) ~[Core.jar:na]
        at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:194) ~[Core.jar:na]
        at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:114) ~[Core.jar:na]
        at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:90) ~[Core.jar:na]
        at org.hibernate.internal.SessionImpl.fireSaveOrUpdate(SessionImpl.java:684) ~[Core.jar:na]
        at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:676) ~[Core.jar:na]
        at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:671) ~[Core.jar:na]
        at org.transitclock.gtfs.DbWriter.writeObject(DbWriter.java:72) ~[Core.jar:na]
        at org.transitclock.gtfs.DbWriter.writeObject(DbWriter.java:67) ~[Core.jar:na]
        at org.transitclock.gtfs.DbWriter.actuallyWriteData(DbWriter.java:153) ~[Core.jar:na]
        at org.transitclock.gtfs.DbWriter.write(DbWriter.java:222) ~[Core.jar:na]
        at org.transitclock.gtfs.GtfsData.processData(GtfsData.java:2725) [Core.jar:na]
        at org.transitclock.applications.GtfsFileProcessor.process(GtfsFileProcessor.java:306) [Core.jar:na]
        at org.transitclock.applications.GtfsFileProcessor.main(GtfsFileProcessor.java:677) [Core.jar:na]

```

**Comment by scrudden** [comment]
tc_issue_117 fixed this.
