### ISSUE TITLE
UpdateTravelTimes failing on develop branch.

### ISSUE THREAD

**Issue by scrudden** [TheTransitClock/transitime#26]

**Comment by scrudden** [comment]
In the recent merge a new readOnly parameter was added to this method which added "-ro" to the database name if this parameter is set to true.

This was being called by the UpdateTravelTimes and causing a NPE.

```
Could not create SessionFactory for dbName=GOHART-ro
java.lang.NullPointerException: null
        at java.util.Hashtable.put(Hashtable.java:460) ~[na:1.8.0_151]
        at java.util.Properties.setProperty(Properties.java:166) ~[na:1.8.0_151]
        at org.hibernate.cfg.Configuration.setProperty(Configuration.java:2027) ~[hibernate-core-4.3.9.Final.jar:4.3.9.Final]
        at org.transitime.db.hibernate.HibernateUtils.createSessionFactory(HibernateUtils.java:120) [classes/:na]
        at org.transitime.db.hibernate.HibernateUtils.getSessionFactory(HibernateUtils.java:201) [classes/:na]
        at org.transitime.db.hibernate.HibernateUtils.getSession(HibernateUtils.java:250) [classes/:na]
        at org.transitime.db.structs.Match.getMatchesCountFromDb(Match.java:355) [classes/:na]
        at org.transitime.core.travelTimes.DataFetcher.readMatches(DataFetcher.java:364) [classes/:na]
        at org.transitime.core.travelTimes.DataFetcher.readData(DataFetcher.java:433) [classes/:na]
        at org.transitime.core.travelTimes.TravelTimesProcessor.readAndProcessHistoricData(TravelTimesProcessor.java:1026) [classes/:na]
        at org.transitime.applications.UpdateTravelTimes.processTravelTimes(UpdateTravelTimes.java:314) [classes/:na]
        at org.transitime.applications.UpdateTravelTimes.manageSessionAndProcessTravelTimes(UpdateTravelTimes.java:369) [classes/:na]
        at org.transitime.applications.UpdateTravelTimes.main(UpdateTravelTimes.java:441) [classes/:na]
```

This database does not exist by default. I am not sure how or where this "-ro" database is to be created.

```
public static SessionFactory getSessionFactory(String agencyId, boolean readOnly) 
			throws HibernateException{
		// Determine the database name to use. Will usually use the
		// projectId since each project has a database. But this might
		// be overridden by the transitime.core.dbName property.
		String dbName = DbSetupConfig.getDbName();
		if (dbName == null)
			dbName = agencyId;
		
		if (readOnly) {
			dbName = dbName + "-ro";
		}
		SessionFactory factory;
		
		synchronized(sessionFactoryCache) {
			factory = sessionFactoryCache.get(dbName);
			// If factory not yet created for this projectId then create it
			if (factory == null || factory.isClosed()) {
				try {
				  logger.info("creating new session factory with readOnly={}", readOnly);
					factory = createSessionFactory(dbName, readOnly);
					sessionFactoryCache.put(dbName, factory);
				} catch (Exception e) {
					logger.error("Could not create SessionFactory for "
							+ "dbName={}", dbName, e);
					throw e;
				}
			}						
		}
		
		return factory;
	}

```

**Comment by scrudden** [comment]
Setting this parameter to false for all calls stops the NPE from occurring when running UpdateTravelTimes.

**Comment by scrudden** [comment]
Fix done in branch tc_issue_24 and merged.
